env: "local"
pg_url: "postgres://postgres:123456@localhost:5432/forum"
access_ttl: 30s
refresh_ttl: 30h
log_level: "debug"
server: "localhost:3000"
grpc_address: "localhost:44044"
secret: "minions-gang"