CREATE TABLE IF NOT EXISTS topics (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)