// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/keshvan/forum-service-sstu-forum/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// PostUsecase is an autogenerated mock type for the PostUsecase type
type PostUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *PostUsecase) Create(_a0 context.Context, _a1 entity.Post) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Post) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Post) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Post) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, postID, userID, role
func (_m *PostUsecase) Delete(ctx context.Context, postID int64, userID int64, role string) error {
	ret := _m.Called(ctx, postID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = rf(ctx, postID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTopic provides a mock function with given fields: ctx, topicID
func (_m *PostUsecase) GetByTopic(ctx context.Context, topicID int64) ([]entity.Post, error) {
	ret := _m.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTopic")
	}

	var r0 []entity.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Post, error)); ok {
		return rf(ctx, topicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Post); ok {
		r0 = rf(ctx, topicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, topicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, postID, userID, role, content
func (_m *PostUsecase) Update(ctx context.Context, postID int64, userID int64, role string, content string) error {
	ret := _m.Called(ctx, postID, userID, role, content)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) error); ok {
		r0 = rf(ctx, postID, userID, role, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostUsecase creates a new instance of PostUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostUsecase {
	mock := &PostUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
